# Generated by Django 5.2.16 on 2026-07-28 17:46

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('repo_url', models.URLField(blank=True)),
                ('api_key', models.CharField(default=core.models.make_api_key, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='core.project')),
            ],
            options={
                'unique_together': {('project', 'test_id')},
            },
        ),
        migrations.CreateModel(
            name='QuarantineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantines', to='core.testcase')),
            ],
        ),
        migrations.CreateModel(
            name='FlakinessScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField(default=0.0)),
                ('ci_low', models.FloatField(default=0.0)),
                ('ci_high', models.FloatField(default=0.0)),
                ('flip_commits', models.IntegerField(default=0)),
                ('observed_commits', models.IntegerField(default=0)),
                ('fail_count', models.IntegerField(default=0)),
                ('run_count', models.IntegerField(default=0)),
                ('avg_duration', models.FloatField(default=0.0)),
                ('impact', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='core.testcase')),
            ],
            options={
                'ordering': ['-impact'],
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_sha', models.CharField(max_length=64)),
                ('branch', models.CharField(default='main', max_length=200)),
                ('ci_run_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error'), ('skipped', 'Skipped')], max_length=10)),
                ('duration', models.FloatField(default=0.0)),
                ('message', models.TextField(blank=True)),
                ('stack_trace', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.testcase')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.testrun')),
            ],
        ),
        migrations.AddIndex(
            model_name='testrun',
            index=models.Index(fields=['project', 'commit_sha'], name='core_testru_project_58c6c5_idx'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['case', 'run'], name='core_testre_case_id_ab1fdd_idx'),
        ),
    ]
