# Generated by Django 5.2.16 on 2026-07-28 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FailureCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centroid', models.JSONField()),
                ('size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_clusters', to='core.project')),
                ('representative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.testresult')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('race_condition', 'Race Condition'), ('test_order_dependency', 'Test Order Dependency'), ('timing_flakiness', 'Timing Flakiness'), ('network', 'Network'), ('resource_leak', 'Resource Leak'), ('unknown', 'Unknown')], max_length=30)),
                ('confidence', models.FloatField(default=0.0)),
                ('explanation', models.TextField(blank=True)),
                ('suggested_fix', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='core.failurecluster')),
            ],
        ),
        migrations.AddField(
            model_name='testresult',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.failurecluster'),
        ),
    ]
