# Generated by Django 5.2.16 on 2026-07-28 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testresult_embedding_failurecluster_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='evidence',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='rag_suggestion',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='FixRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_sha', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fix', to='core.failurecluster')),
            ],
        ),
    ]
