# Generated by Django 5.2.16 on 2026-07-28 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_diagnosis_evidence_diagnosis_rag_suggestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('reproduced', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=30)),
                ('confidence', models.FloatField(default=0.0)),
                ('explanation', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='core.failurecluster')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('tool', models.CharField(max_length=100)),
                ('tool_input', models.JSONField(default=dict)),
                ('tool_output', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.agentrun')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
